# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='ano',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='modelo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
