# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_auto_20180323_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='carro',
            name='valor',
            field=models.DecimalField(decimal_places=0, max_digits=300, null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='fabricante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carros.Fabricante'),
        ),
    ]
