# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_auto_20180323_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=300, null=True),
        ),
    ]
